services:
  #=== PGADMIN ===
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - auth_db

  #=== REDIS ===
  redis:
    image: redis:7-alpine
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - app-network

  #=== RABBITMQ ===
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network
  #=== AUTH ===
  auth:
    image: node:22.16.0-alpine
    container_name: auth_service
    working_dir: /app
    volumes:
      - ../auth:/app
    command: sh -c "npm i && npm run start:dev"
    # ports:
    #   - "3001:3001"
    expose:
      - "3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth_db
      - redis
    networks:
      - app-network
  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  #=== NOTIFICATION ===
  notification:
    image: node:22.16.0-alpine
    container_name: notification_service
    working_dir: /app
    volumes:
      - ../notification:/app
    command: sh -c "npm i && npm run start:dev"
    expose:
      - "3006"
    environment:
      - NODE_ENV=development
    depends_on:
      - rabbitmq
    networks:
      - app-network

  #=== USER ===
  user:
    image: node:22.16.0-alpine
    container_name: user_service
    working_dir: /app
    volumes:
      - ../user:/app
    command: sh -c "npm i && npm run start:dev"
    expose:
      - "3002"
    # ports:
    #   - "3002:3002"
    environment:
      - NODE_ENV=development
    depends_on:
      - user_db
    networks:
      - app-network
  user_db:
    image: postgres:15-alpine
    container_name: user_db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - app-network
  #=== PET ===
  pet:
    image: node:22.16.0-alpine
    container_name: pet_service
    working_dir: /app
    volumes:
      - ../pet:/app
    command: sh -c "npm i && npm run start:dev"
    # ports:
    #   - "3003:3003"
    expose:
      - "3003"
    environment:
      - NODE_ENV=development
    depends_on:
      - pet_db
    networks:
      - app-network
  pet_db:
    image: postgres:15-alpine
    container_name: pet_db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pet_db
    volumes:
      - pet_db_data:/var/lib/postgresql/data
    networks:
      - app-network
  #=== HEALTH ===
  health:
    image: node:22.16.0-alpine
    container_name: health_service
    working_dir: /app
    volumes:
      - ../health:/app
    command: sh -c "npm i && npm run start:dev"
    # ports:
    #   - "3004:3004"
    expose:
      - "3004"
    environment:
      - NODE_ENV=development
    depends_on:
      - health_db
    networks:
      - app-network
  health_db:
    image: postgres:15-alpine
    container_name: health_db
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=health_db
    volumes:
      - health_db_data:/var/lib/postgresql/data
    networks:
      - app-network
  #=== GATEWAY ===
  gateway:
    image: node:22.16.0-alpine
    container_name: gateway_service
    working_dir: /app
    volumes:
      - ../gateway:/app
    command: sh -c "npm i && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    # depends_on:
    #   - auth
    #   - user
    #   - pet
    #   - health
    networks:
      - app-network
  #=== MEDIA ===
  media:
    image: node:22.16.0-alpine
    container_name: media_service
    working_dir: /app
    volumes:
      - ../media:/app
    command: sh -c "npm i && npm run start:dev"
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    depends_on:
      - media_db
    networks:
      - app-network

  media_db:
    image: postgres:15-alpine
    container_name: media_db
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=media_db
    volumes:
      - media_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  #=== APP WEB ===
  app:
    image: node:22.16.0-alpine
    container_name: app_web
    working_dir: /app
    volumes:
      - ../app:/app
    command: sh -c "npm i && npm run web"
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_PUBLIC_API_URL=http://localhost:3000/api
      - EXPO_PUBLIC_MEDIA_URL=http://localhost:3005/api
    depends_on:
      - gateway
    networks:
      - app-network

volumes:
  auth_db_data:
  user_db_data:
  pet_db_data:
  health_db_data:
  pgadmin_data:
  rabbitmq_data:
  media_db_data:


networks:
  app-network:
